#!/bin/sh

# Bash
ln -s ~/dotfiles/bash_profile ~/.bash_profile
ln -s ~/dotfiles/bashrc ~/.bashrc
ln -s ~/dotfiles/bash_completion ~/.bash_completion
ln -s ~/dotfiles/sh ~/.sh

# Vim
ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/gvimrc ~/.gvimrc
ln -s ~/dotfiles/vim ~/.vim

# Neovim
ln -s ~/dotfiles/init.vim ~/.config/nvim/init.vim
ln -s ~/dotfiles/coc-settings.json ~/.config/nvim/coc-settings.json

# IDE Vim plugins
ln -s ~/dotfiles/ideavimrc ~/.ideavimrc
ln -s ~/dotfiles/vrapperrc ~/.vrapperrc

# Git
ln -s ~/dotfiles/git_template ~/.git_template
git config --global init.templatedir '~/.git_template'

# Misc
ln -s ~/dotfiles/ackrc ~/.ackrc
ln -s ~/dotfiles/dotctags ~/.ctags

