
# tap repositories and their packages

tap homebrew/core

tap rcmdnk/file
brew brew-file

tap jenv/jenv

brew autoconf
brew automake
brew awscli
brew cscope
brew ctags
brew findutils
brew fontconfig
brew freetype
brew gd
brew gdbm
brew gettext
brew gflags
brew git
brew glib
brew graphviz
brew icu4c
brew jemalloc
brew jenv
brew jpeg
brew jq
brew krb5
brew kubernetes-cli
brew libffi
brew libidn2
brew libpng
brew libsodium
brew libsvg
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvterm
brew libyaml
brew lua
brew luajit
brew lzo
brew mas
brew maven
brew msgpack
brew ncurses
brew neovim
brew node
brew opa
brew openssl@1.1
brew pandoc
brew pax-construct
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew plantuml
brew readline
brew redis
brew ripgrep
brew sphinx-doc
brew svg2pdf
brew tcl-tk
brew telnet
brew unibilium
brew vert.x
brew webp
brew wget
brew xz
brew yarn
brew zookeeper
brew zsh

tap adoptopenjdk/openjdk
cask adoptopenjdk11
cask adoptopenjdk8

tap homebrew/cask-fonts
cask font-inconsolata
cask font-meslo-lg-nerd-font

tap homebrew/services

tap homebrew/cask
cask 1password # /Applications/1Password 7.app
cask dropbox # /Applications/Dropbox.app
cask google-chrome # /Applications/Google Chrome.app
cask docker
cask firefox
cask insomnia
cask iterm2 # /Applications/iTerm.app
cask onyx
cask postman
cask visual-studio-code
cask vlc # /Applications/VLC.app

# App Store applications
appstore 406056744 Evernote (10.8.4)
appstore 682658836 GarageBand (10.3.5)
appstore 408981434 iMovie (10.2.2)
appstore 408981381 iPhoto (9.6.1)
appstore 409183694 Keynote (10.3.9)
appstore 409203825 Numbers (10.3.9)
appstore 409201541 Pages (10.3.9)
appstore 803453959 Slack (4.12.2)
