
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew awscli
brew cairo
brew cscope
brew ctags
brew docker
brew elasticsearch
brew findutils
brew fontconfig
brew freetype
brew fribidi
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gflags
brew git
brew glib
brew gobject-introspection
brew graphite2
brew graphviz
brew gts
brew harfbuzz
brew icu4c
brew jasper
brew jemalloc
brew jenv
brew jpeg
brew jq
brew krb5
brew kubernetes-cli
brew libffi
brew libidn2
brew libpng
brew libpthread-stubs
brew librsvg
brew libsodium
brew libsvg
brew libsvg-cairo
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew logstash
brew lua
brew luajit
brew luajit-openresty
brew luv
brew lzo
brew mas
brew maven@3.5
brew mpdecimal
brew msgpack
brew ncurses
brew neovim
brew netpbm
brew node
brew oniguruma
brew opa
brew openjdk
brew openjdk@11
brew openssl@1.1
brew pandoc
brew pango
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew plantuml
brew python@3.9
brew readline
brew redis
brew ripgrep
brew sphinx-doc
brew sqlite
brew svg2pdf
brew tcl-tk
brew telnet
brew unibilium
brew vert.x
brew webp
brew wget
brew xorgproto
brew xz
brew yarn
brew zookeeper
brew zsh

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-inconsolata
cask font-meslo-lg-nerd-font

tap homebrew/services

tap homebrew/cask
cask 1password
cask dbeaver-community
cask dropbox
cask firefox
cask google-chrome
cask insomnia
cask iterm2
cask onyx
cask openvpn-connect
cask postman
cask visual-studio-code
cask vlc

tap adoptopenjdk/openjdk
cask adoptopenjdk11
cask adoptopenjdk8

tap jenv/jenv

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 406056744 Evernote (10.9.10)
appstore 682658836 GarageBand (10.3.5)
appstore 408981434 iMovie (10.2.3)
appstore 409183694 Keynote (11.0)
appstore 409203825 Numbers (11.0)
appstore 409201541 Pages (11.0)
appstore 803453959 Slack (4.13.0)
appstore 497799835 Xcode (12.4)
